## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/

/etc/firewall.user
/etc/dropbear/authorized_keys
/root/oasis_restore.sh
/root/sync_ipv6_hosts.sh
/root/sync_agh_ipv6_clients.sh
/root/check_wg_197.sh
/root/show_ipv6_clients.sh
/etc/adguardhome/adguardhome.yaml
/etc/adguardhome/certs/
/etc/uhttpd.crt
/etc/uhttpd.key
